log_level: debug
log_format: json
polling_interval: 10s
graceful_timeout: 30s

# API Configuration
api_base_url: "https://observatorium-api.example.com"
api_tenant: "default"
label_selector: "private=false,rhobs-synthetics/status=pending"

# Kubernetes Configuration
namespace: "monitoring"