apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-agent-config
  labels:
    name: prometheus-agent-config
  namespace: rhobs-int
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'blackbox-probes'
        metrics_path: /probe
        params:
          module: [http_2xx]
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
              - rhobs-int
        relabel_configs:
          # First, find the endpoint for the blackbox-exporter service
          - source_labels: [__meta_kubernetes_service_name]
            regex: 'blackbox-exporter'
            action: keep

          # Use the 'probe' resource's labels to find the actual target URL
          - source_labels: [__meta_kubernetes_endpoints_name]
            regex: 'probe-.*'
            action: keep

          # Use the annotation from the Probe to get the target URL
          - source_labels: [__meta_kubernetes_endpoints_annotation_monitoring_coreos_com_target]
            target_label: __param_target
            action: replace

          # Use the __meta_kubernetes_service_name to set the 'instance' label
          - source_labels: [__meta_kubernetes_endpoints_annotation_monitoring_coreos_com_target]
            target_label: instance
            action: replace

          # Finally, rewrite the scrape address to the blackbox exporter
          - target_label: __address__
            replacement: blackbox-exporter:9115

    remote_write:
    - url: 'http://thanos-receive-router-rhobs.rhobs-int.svc.cluster.local:19291/api/v1/write'
